feat: Profile Card
neynarxyz/react pull request #2
Opened 2024-05-21 05:52 UTC by syntag

Adds `ProfileCard` component and `NeynarProfileCard` wrapper, which uses the Neynar API to fetch user data with `fid` and `viewerFid`.

**New features:**
- Added global theming support for :sunny: light and :crescent_moon: dark modes
- Added `Box`, `VBox`, and `HBox` shared component for layouts

**Demo:**

https://github.com/neynarxyz/react/assets/10079423/05d32ff0-a100-4a93-8488-6f88d10fc4a8

2024-05-22 17:14 UTC, manan19 commented on src/components/stories/NeynarProfileCard/NeynarProfileCard.stories.tsx
> +  location: "Boston, USA",
location isn't available on the protocol, so we should probably remove this

2024-05-26 16:21 UTC, MrKevinOConnell reviewed
I think this looks pretty good:

light + dark modes are good - would be good imo to add custom css styling but dont need that for v1
https://github.com/pugson/react-farcaster-embed

2024-05-28 16:47 UTC, Shreyaschorge requested changes

2024-05-28 16:47 UTC, Shreyaschorge commented on src/contexts/NeynarContextProvider.tsx
Removal of the following code is a breaking change in the SDK.

It'll not add `.theme-light` or `.dark-theme` class to the root thus the theme properties associated with these themes (i.e. `--palette-background`, `--palette-border` etc) will not be present in the DOM.

`withThemeByClassName` will only work for storybook but we need these properties to be present in the DOM as well.

Is there a better way to add these classes to the root of the DOM?
```
useEffect(() => {
    const root = document.querySelector(":root");
    if (root) {
      if (theme === "light") {
        root.classList.add("theme-light");
        // root.classList.remove("theme-dark");
      }
      // else {
      //   root.classList.add("theme-dark");
      //   root.classList.remove("theme-light");
      // }
    }
  }, [theme]);
  ```

2024-05-28 16:47 UTC, Shreyaschorge commented on src/components/stories/NeynarProfileCard.stories.tsx
> +WithUser.args = {
WithUser is breaking right now, even after being logged in, can we use the user from the  Neynar Context, i.e. if we signed into using NeynarAuthButon that user should be filled into this

@manan19 Should the components in SDK remember the state of the logged-in user? Or do we want to give flexibility to the devs to add their own state or should we do both?

![image](https://github.com/neynarxyz/react/assets/37466979/18a8c189-8cce-45f9-baed-6cdd97082f32)

2024-06-10 16:49 UTC, Shreyaschorge commented on src/components/stories/NeynarProfileCard.stories.tsx
> +WithUser.args = {
This was caused due to `NEYNAR_API_URL` was the part of .env which should not be the case

2024-06-10 19:19 UTC, merged